version: "3.9"
services:
  noxbackup:
    build: .
    volumes:
      - .:/fastapi
    ports:
      - "9527:5000"
    command: uvicorn main:app --reload --host=0.0.0.0 --port=5000
    restart: unless-stopped
